# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f68efb384225de2fa35cfa2af37613decc5a3a124722172c668fc1ab19ce5fdade86d96888711b00ed7bb24f08897a3311e698194ea7272f34dc508bfda2725

test:
  secret_key_base: 82f479998665335ecec98f5179fa7f0242628677c6cc3450c1d54d0dccf7ef0d0d52b4858cb6999d37f08d8675b15b8b53eb00a36a97a15bb521d454f8c0d42b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
